import { NearbyMatch } from './types';

export const MOCK_NEARBY: NearbyMatch[] = [
  {
    chain: {
      id: 'nandos',
      name: "Nando's",
      aliases: ["Nando's Peri-Peri", 'Nandos'],
      logo: 'https://www.google.com/s2/favicons?domain=nandos.co.uk&sz=128',
      cuisine: 'Chicken',
      websiteUrl: 'https://www.nandos.co.uk',
      deliveryLinks: {
        uberEats: 'https://www.ubereats.com/store/nandos',
        deliveroo: 'https://deliveroo.co.uk/menu/nandos',
      },
      meals: [
        {
          id: 'n1',
          chainId: 'nandos',
          name: 'Grilled Chicken Breast',
          photo: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=400',
          calories: 380,
          protein: 42,
          carbs: 12,
          fat: 14,
        },
        {
          id: 'n2',
          chainId: 'nandos',
          name: 'Supergrain Salad',
          photo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
          calories: 290,
          protein: 18,
          carbs: 35,
          fat: 8,
        },
        {
          id: 'n3',
          chainId: 'nandos',
          name: 'Chicken Wrap',
          photo: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400',
          calories: 420,
          protein: 32,
          carbs: 28,
          fat: 16,
        },
        {
          id: 'n4',
          chainId: 'nandos',
          name: 'Butterfly Chicken',
          photo: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400',
          calories: 340,
          protein: 52,
          carbs: 2,
          fat: 12,
        },
      ],
    },
    distance: 0.3,
    latitude: 51.5074,
    longitude: -0.1278,
    address: '123 High Street, London',
  },
  {
    chain: {
      id: 'pizzaexpress',
      name: 'Pizza Express',
      aliases: ['PizzaExpress'],
      logo: 'https://www.google.com/s2/favicons?domain=pizzaexpress.com&sz=128',
      cuisine: 'Italian',
      websiteUrl: 'https://www.pizzaexpress.com',
      deliveryLinks: {
        uberEats: 'https://www.ubereats.com/store/pizza-express',
        deliveroo: 'https://deliveroo.co.uk/menu/pizza-express',
      },
      meals: [
        {
          id: 'pe1',
          chainId: 'pizzaexpress',
          name: 'Leggera Margherita',
          photo: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
          calories: 340,
          protein: 14,
          carbs: 42,
          fat: 10,
        },
        {
          id: 'pe2',
          chainId: 'pizzaexpress',
          name: 'Nicoise Salad',
          photo: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
          calories: 260,
          protein: 22,
          carbs: 18,
          fat: 12,
        },
        {
          id: 'pe3',
          chainId: 'pizzaexpress',
          name: 'Pollo Forza',
          photo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
          calories: 480,
          protein: 36,
          carbs: 48,
          fat: 14,
        },
      ],
    },
    distance: 0.7,
    latitude: 51.5094,
    longitude: -0.1338,
    address: '45 Baker Street, London',
  },
  {
    chain: {
      id: 'wagamama',
      name: 'Wagamama',
      aliases: ['wagamama'],
      logo: 'https://www.google.com/s2/favicons?domain=wagamama.com&sz=128',
      cuisine: 'Japanese',
      websiteUrl: 'https://www.wagamama.com',
      deliveryLinks: {
        uberEats: 'https://www.ubereats.com/store/wagamama',
        deliveroo: 'https://deliveroo.co.uk/menu/wagamama',
      },
      meals: [
        {
          id: 'w1',
          chainId: 'wagamama',
          name: 'Chicken Katsu Curry',
          photo: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400',
          calories: 580,
          protein: 34,
          carbs: 64,
          fat: 18,
        },
        {
          id: 'w2',
          chainId: 'wagamama',
          name: 'Grilled Chicken Ramen',
          photo: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=400',
          calories: 420,
          protein: 38,
          carbs: 40,
          fat: 10,
        },
        {
          id: 'w3',
          chainId: 'wagamama',
          name: 'Yasai Pad Thai',
          photo: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400',
          calories: 350,
          protein: 12,
          carbs: 52,
          fat: 8,
        },
      ],
    },
    distance: 1.2,
    latitude: 51.5134,
    longitude: -0.1398,
    address: '78 Regent Street, London',
  },
  {
    chain: {
      id: 'leon',
      name: 'LEON',
      aliases: ['Leon', 'LEON Naturally Fast Food'],
      logo: 'https://www.google.com/s2/favicons?domain=leon.co&sz=128',
      cuisine: 'Mediterranean',
      websiteUrl: 'https://leon.co',
      deliveryLinks: {
        uberEats: 'https://www.ubereats.com/store/leon',
        deliveroo: 'https://deliveroo.co.uk/menu/leon',
      },
      meals: [
        {
          id: 'l1',
          chainId: 'leon',
          name: 'Grilled Chicken LOVe Box',
          photo: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
          calories: 410,
          protein: 38,
          carbs: 32,
          fat: 14,
        },
        {
          id: 'l2',
          chainId: 'leon',
          name: 'Salmon Fillet Box',
          photo: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
          calories: 380,
          protein: 30,
          carbs: 28,
          fat: 16,
        },
        {
          id: 'l3',
          chainId: 'leon',
          name: 'Vegan Meatball Hot Box',
          photo: 'https://images.unsplash.com/photo-1529059997568-3d847b1154f0?w=400',
          calories: 320,
          protein: 16,
          carbs: 42,
          fat: 10,
        },
      ],
    },
    distance: 1.8,
    latitude: 51.5154,
    longitude: -0.1418,
    address: '22 Oxford Street, London',
  },
  {
    chain: {
      id: 'chipotle',
      name: 'Chipotle',
      aliases: ['Chipotle Mexican Grill'],
      logo: 'https://www.google.com/s2/favicons?domain=chipotle.com&sz=128',
      cuisine: 'Mexican',
      websiteUrl: 'https://www.chipotle.com',
      deliveryLinks: {
        uberEats: 'https://www.ubereats.com/store/chipotle',
        doordash: 'https://www.doordash.com/store/chipotle',
      },
      meals: [
        {
          id: 'c1',
          chainId: 'chipotle',
          name: 'Chicken Burrito Bowl',
          photo: 'https://images.unsplash.com/photo-1623653387945-2fd25214f8fc?w=400',
          calories: 510,
          protein: 46,
          carbs: 40,
          fat: 18,
        },
        {
          id: 'c2',
          chainId: 'chipotle',
          name: 'Sofritas Salad',
          photo: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
          calories: 350,
          protein: 18,
          carbs: 30,
          fat: 16,
        },
        {
          id: 'c3',
          chainId: 'chipotle',
          name: 'Steak Tacos (3)',
          photo: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400',
          calories: 450,
          protein: 40,
          carbs: 36,
          fat: 14,
        },
      ],
    },
    distance: 2.4,
    latitude: 51.5174,
    longitude: -0.1438,
    address: '55 Tottenham Court Road, London',
  },
];
